### ISSUE TITLE
Consider exec'ing Argcfile

### ISSUE THREAD

**Issue by CGamesPlay** [sigoden/argc#221]
A small change which would be a bit more hygienic is to exec the Argcfile.sh when it's used.

Consider an Argcfile.sh like this one:
```bash
#!/usr/bin/env bash

main() {
    exec bash
}

eval "$(argc --argc-eval "$0" "$@")"
```

When we run this, it results in a process tree like this one:

```
$ ps uf
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
ubuntu      2034  0.1  0.0 247380 17112 pts/1    Ss   10:40   0:06 -fish
ubuntu     36428  0.0  0.0   3304     4 pts/1    Sl   11:53   0:00  \_ argc
ubuntu     36430  1.0  0.0   8664  5436 pts/1    S+   11:53   0:00      \_ bash
```

The feature request is for argc (PID 36428) to use `exec` when it runs the Argcfile.sh, instead of starting it as a child process. This is minor but would be slightly cleaner.

**Comment by sigoden** [comment]
@CGamesPlay 
I don't understand what you said.

fish runs `argc`
argc locates Argcfile.sh and runs`bash Argcfile.sh`
bash does the rest

Which part needs improvement?

**Comment by CGamesPlay** [comment]
Instead of running `bash Argcfile.sh` as a subcommand, it should exec `bash Argcfile.sh`. This would *replace* the argc process with the bash process. The desired process tree would look like this:

```
$ ps uf
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
ubuntu      2034  0.1  0.0 247380 17112 pts/1    Ss   10:40   0:06 -fish
ubuntu     36430  1.0  0.0   8664  5436 pts/1    S+   11:53   0:00  \_ bash
```

**Comment by sigoden** [comment]
Three is no way to get rid of argc process in the ps tree.

Bash is invoked outside of the script, no exec exists.

**Comment by CGamesPlay** [comment]
Yes, bash is invoked by `argc` as a child process. The request is to `exec` the process instead of `spawn`ing it. Basically, switch to [exec](https://doc.rust-lang.org/std/os/unix/process/trait.CommandExt.html#tymethod.exec) instead of [status](https://github.com/sigoden/argc/blob/main/src/bin/argc/main.rs#L148). By using `exec`, the `argc` process itself is replaced by `bash`. Then the `Argcfile.sh` can `exec` another bash, resulting in the desired ps tree.

**Comment by sigoden** [comment]
Does exec return exit statuscode?

**Comment by CGamesPlay** [comment]
No, it actually doesn't return at all. The `argc` process would be entirely replaced by the target command. However, because the process is replaced in-place, the parent of `argc` will continue waiting for the new process, and will receive the exit code from the new process once the new process finishes.
