### ISSUE TITLE
Inconsistent behavior when Argcfile.sh is a symlink

### ISSUE THREAD

**Issue by CGamesPlay** [sigoden/argc#306]
Hi sigoden, I was recently setting up a repository where I needed to symlink the Argcfile into a different location. I wanted to do this specifically because I wanted argc's directory handling (so that the script would always be run from the directory with the symlink). 

The behavior I observe:
- `argc --argc-script-path` prints the path to the symlink
- `argc` will cd into the directory containing the target of the symlink.

I feel like one of these exhibits the wrong behavior. For me, I'd prefer that argc did not resolve the symlink before changing directory (since I can't imagine a time when that behavior would be useful), but if this is desired behavior, then `--argc-script-path` should be consistent with it.

Thanks as always for the great software package.

**Comment by sigoden** [comment]
fixed in #304
