### ISSUE TITLE
Dotenv file not read

### ISSUE THREAD

**Issue by kerruba-milkman** [sigoden/argc#307]
Hello, thanks for this amazing project which is helping me a lot in standardizing my scripts and simplify how to configure them using flags/args etc.

I'm having some issues with the `@env` and `@meta dotenv` annotations.

Probably I'm misunderstanding the way these annotations are meant  to be used, but my expectation was that if a `.env` file was present in the current folder, it was read and used to override the default values from the `@env` annotation.

For example, in my script I have these annotations
```bash
# @env MY_PROFILE=someprofile The profile used
# @meta dotenv
```

And  I've created a `.env` file in the same folder filled like this
```
MY_PROFILE=special
```

When I print the actual env variable I'm  getting this
```bash
echo $MY_PROFILE => "someprofile" 
# I was expecting instead "special"
```

Is this the expected behavior? There's a way to override the env using the .env file?

Many thank

**Comment by kerruba-milkman** [comment]
Sorry I've tested out  the fix by building the binary locally, but I'm not sure the problem was actually fixed.

Having this headers at the start of the  file
```bash
...
# @env MY_PROFILE=my-profile
# @meta dotenv
```

And this `.env` file
```
MY_PROFILE=special
```
I'm  still seeing the behavior where the env-variable  uses the `default` value rather than the one provided in  the `.env` file, but to me  that seems counterintuitive as the default value for the env should be used if not already defined in the command line or in  the .env file.
What do you think?

**Comment by sigoden** [comment]
I confirmed the bug have been fixed.

Please check argc path with `which argc`. is the path point to the building the binary? @kerruba-milkman

**Comment by kerruba-milkman** [comment]
Sorry, I'm not used to the rust ecosystem so the `cargo build --release --locked` didn't build the binary the way I was expecting.  
Instead I've used `cargo install` pointing directly to the git repo and I can confirm the fix is in place. Thanks a lot
