### ISSUE TITLE
"command not found" when using `@cmd` in a minimal file

### ISSUE THREAD

**Issue by phip1611** [sigoden/argc#348]
Hey there! I'm having trouble with the `# @cmd` directive.
This is my minimal reproducer. I'm using `argc` at version `1.20.1`:

**./deploy.sh**

```bash
#!/usr/bin/env bash

eval "$(argc --argc-eval "$0" "$@")"

# @cmd Deploys all VM hosts.
function vm-hosts() {
  echo deploying VM hosts
}

# @cmd Deploy the VM.
function vm() {
  echo deploying VM
}
```

When I run `./deploy.sh --help`, it says:

```
USAGE: deploy <COMMAND>

COMMANDS:
  vm-hosts  Deploys all VM hosts.
  vm        Deploy the VM.
```

But when I run `./deploy.sh vm` or `./deploy.sh vm-hosts`, it says

> ./deploy.sh: line 7: vm: command not found

What's going on here?

**Comment by sigoden** [comment]
In Bash, a function must be defined before it can be called. You need to place argc-eval at the end of the script file.

```diff
#!/usr/bin/env bash

-- eval "$(argc --argc-eval "$0" "$@")"

# @cmd Deploys all VM hosts.
function vm-hosts() {
  echo deploying VM hosts
}

# @cmd Deploy the VM.
function vm() {
  echo deploying VM
}

++ eval "$(argc --argc-eval "$0" "$@")"

```

**Comment by phip1611** [comment]
Ahhh, thanks! Got it
