### ISSUE TITLE
question about autocompletion for absolute paths to executable

### ISSUE THREAD

**Issue by jokeyrhyme** [sigoden/argc#350]
Howdy, thanks so much for sharing this interesting and very helpful project! <3

I did have what is probably a weird question: I'm noticing that it doesn't complete certain cases as I'd expect

- `argc --argc-compgen nushell "" ~/.dot` -> empty results, but I'd expect ~/.dotfiles because this directory exists
- `argc --argc-compgen nushell "" /us` -> empty results, but I'd expect /usr because this directory exists
- `argc --argc-compgen nushell "" /usr/bin/s` -> empty results, but there are loads of executables starting with `/usr/bin/s` so there should be up to the maximum number of suggestions (10 by default, I think)

I _think_ the issue is that `~/.dotfiles`, `/usr`, `/usr/bin/sh` aren't commands, but absolute paths to executables (assuming directories have the execute permission bit), but I'm not quite sure how to get these to work, or if it's really in-scope for `argc` to handle these ...

Anyhow, this isn't remotely urgent, just thought I'd let you know in case you had some thoughts :)

Thanks again!

**Comment by sigoden** [comment]
@jokeyrhyme 
The ` --argc-compgen` syntax is:
```
argc --argc-compgen <SHELL> <FILE> <ARGS>  Generate completion candidates
```
You missed the `cmd`.
```
argc --argc-compgen nushell "" ls ~/.dot
```

**Comment by jokeyrhyme** [comment]
> You missed the cmd.

That was intentional

My use case is executing scripts and other executable files that are not in PATH, by typing in their absolute file path, hopefully with some completions to speed it up

**Comment by sigoden** [comment]
The completion for the command itself is handled by the shell, not the external completer.

**Comment by jokeyrhyme** [comment]
Ah, thanks! <3

**Comment by jokeyrhyme** [comment]
Ah, I found this: https://www.nushell.sh/book/custom_completions.html#external-completions

> When the closure returns unparsable json (e.g., an empty string) it defaults to file completion.

So I've updated my `argc` integration in `nu` to:

```
    def _argc_completer [args: list<string>] {
        ^argc --argc-compgen nushell "" ...$args
            | split row "\n"
            | each { |line| $line | split column "\t" value description }
            | flatten
    }

    let external_completer = {|spans|
        if ($spans | length) < 2 {
            '' # default completer
        } else {
            _argc_completer $spans
        }
    }

    $env.config.completions.external.enable = true
    $env.config.completions.external.completer = $external_completer
```
