### ISSUE TITLE
Comment tag for examples

### ISSUE THREAD

**Issue by xsYf6tdq8** [sigoden/argc#357]
Hi. I'm porting quite a few scripts to argc. In my own 'getopts' based implementation I always added EXAMPLES to the help text of any script. Some examples never hurt usability.

I'm now replicating this functionality by using/abusing the multi line feature of the `@cmd` tag. The `EXAMPLES` section is also quite common in MAN pages but of course this section is not generated using the `@cmd` tag.

The following is an example of how I now create `EXAMPLES` in the help text.

```
# @cmd Do something to something
# 
# This command can do something to something else.
# 
# EXAMPLES:
#   prog1 change object1 object2
#   prog1 create object3 category1
#   prog1 delete object3 category1
# 
```

Thanks for your work and who knows I might even try to collaborate on the code.

**Comment by sigoden** [comment]
Examples are just part of the description; we don't think there's a need to list them separately.
