### ISSUE TITLE
[FR] Colored help

### ISSUE THREAD

**Issue by murlakatamenka** [sigoden/argc#37]
Can we have colored helped, please? I haven't seen anything about color in README or issues.

`clap`'s default color choice is auto, i.e. when terminal supports it:

https://docs.rs/clap/3.2.17/clap/enum.ColorChoice.html#variant.Auto

**Comment by sigoden** [comment]
I disabled it for simplicity, since you asked for it, I will enable it later

**Comment by murlakatamenka** [comment]
Thanks, I think colors make a better terminal UX

**Comment by murlakatamenka** [comment]
Thanks! :+1:
