### ISSUE TITLE
[gdb under argc] ctrl-c leads to terminate, not interrupt

### ISSUE THREAD

**Issue by jminh** [sigoden/argc#49]
In gdb the default behavior of ctrl-c is to interrupt the process. For example:

```
  (gdb) c
  Continuing.
  ^C
  Thread 1 "main" received signal SIGINT, Interrupt.
  0x00002aaab428480d in nanosleep () from /lib64/libc.so.6
  (gdb)
```
But if run gdb from argc, ctrl-c would terminate the gdb debug process.

```
# @cmd debug
debug () {
  gdb -p `pgrep main` \
     -ex 'c'
  #exec gdb -p `pgrep main` \
  #   -ex 'c'
}
```

```
argc debug
 # in gdb 
 # ctrl-c would terminate the debug process.
```
Its exit code is 130 and the output is like:

```
  ^C
  
  Thread 1 "main" received signal SIGINT, Interrupt.
  [Switching to Thread 0x2aaaaab30640 (LWP 177491)]
  0x00002aaab5bfa80d in nanosleep () from /lib64/libc.so.6
  (130)
```

Is there any solution or workaround to not terminate the gdb?

**Comment by sigoden** [comment]
argc is now just a command line argument parsing tool. The task runner related functions were moved into [runme](https://github.com/sigoden/runme).

sigoden/runme#2  fixed this issue.
