### ISSUE TITLE
Add ability to force command string

### ISSUE THREAD

**Issue by lionelnicolas** [sigoden/argc#93]
As command strings are based on the shell function name, it's not possible to use dashes.

For example, using the following script:

```sh
#!/bin/sh

# @describe This is a test

# @cmd      Start the service
start_service() {
    echo do stuff
}

argc $0 "$@"
```

The help function is:

```
This is a test

USAGE: argc-test <COMMAND>

COMMANDS:
  start_service  Start the service

```

I would like to be able to use dashes instead of underscores as word-delimiters in command names:

```
This is a test

USAGE: argc-test <COMMAND>

COMMANDS:
  start-service  Start the service

```

I see two potential solutions:
 * replace all underscores (`_`) with dashes (`-`) in command names (maybe not by default, for example by adding a flag for that)
 * or (probably better) add a `@name` flag to be able to force the command name:

```sh
# @cmd      Start the service
# @name     start-service
start_service() {
    echo do stuff
}
```

I know it's possible to use `@alias` to make it work, but I would prefer to hide the `service_start` function name in this output:

```
This is a test

USAGE: argc-test <COMMAND>

COMMANDS:
  start_service  Start service [aliases: start-service]
```

Let me know what you think.

And thanks for this great tool ! Can't wait to see the upcoming v1.0.0 released.

EDIT: looks like v1.0.0 was released 30 minutes ago :smile:

**Comment by sigoden** [comment]
Why not update you cmd function name?
```
#!/usr/bin/env bash

# @describe This is a test

# @cmd
start-service() {
    :;
}

eval "$(argc --argc-eval "$0" "$@")"
```

```
This is a test

USAGE: test <COMMAND>

COMMANDS:
  start-service  Start the service
```

Function names or command names are actually more free than you think
```
# @cmd
test:foo() {
  :;
}

# @cmd
test@foo() {
  :;
}

# @cmd
test-foo() {
  :;
}

# @cmd
test_foo() {
  :;
}

# @cmd
test.foo() {
  :;
}
```

```
COMMANDS:
  test:foo  
  test@foo  
  test-foo  
  test_foo  
  test.foo  
```

**Comment by sigoden** [comment]
I even choose `::`  as marker for nested subcommands.

```
#!/usr/bin/env bash

# @cmd
cmd() {
    :;
}

# @cmd
cmd::foo() {
    :;
}

# @cmd
cmd::bar() {
    :;
}


eval "$(argc --argc-eval "$0" "$@")"
```
Run `./test.sh -h`
```
USAGE: test <COMMAND>

COMMANDS:
  cmd  
```
Run `./test.sh cmd -h`
```
USAGE: test cmd <COMMAND>

COMMANDS:
  foo  
  bar  
```

**Comment by lionelnicolas** [comment]
Oh yeah you're right.

In fact I'm always writing POSIX-compatible scripts and using `#!/bin/sh` as shebang, so using `test-func()` or `test::func()` results in:

```
#~ /tmp/argc-test                                                                                                  
/tmp/argc-test: 7: Syntax error: Bad function name
```

I might be too old fashion haha, but I can change my shebangs to `/bin/bash`. In fact the main reason why I'm always using `/bin/sh` is because I used to write scripts for embedded devices where I only had low footprint POSIX shell available.

Thanks for the hint.

**Comment by clysto** [comment]
Thank you for your suggestion! Not being able to explicitly specify the command name can indeed cause naming conflicts and may result in existing commands being unintentionally overwritten. Allowing users to set the command name directly (for example, with a @name flag) would help prevent such issues and provide greater flexibility. This improvement would be very helpful for avoiding collisions and ensuring custom command naming.
